name: Conventional PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Validates the pull request
        uses: Namchee/conventional-pr@v0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          issue: false